// src/main/java/com/ims/model/Product.java
package com.ims.model; // This package declaration MUST match the folder structure.

import java.io.Serializable; // Recommended for objects that might be passed over a network or stored in session.

public class Product implements Serializable {

    private static final long serialVersionUID = 1L; // For serialization, helps with versioning.
    private int productId;
    private String productName;
    private String description;
    private double price;
    private int quantity;
    private int categoryId; // Foreign key to categories table
    private int brandId;    // Foreign key to brands table
    private String imagePath; // Path to the product image on the server
    private String status;    // e.g., "Available", "Out of Stock", "Discontinued"

    /**
     * Default constructor.
     * Required by many frameworks (like Jakarta EE/Spring) and useful for creating an empty Product object
     * and then setting its properties using setters.
     */
    public Product() {
        // Default constructor
    }

    /**
     * Constructor for creating new Product objects without an ID (ID will be generated by DB).
     * Use this when you are creating a new product record to insert into the database.
     *
     * @param productName The name of the product.
     * @param description A brief description of the product.
     * @param price The selling price of the product.
     * @param quantity The current stock quantity of the product.
     * @param categoryId The ID of the category this product belongs to.
     * @param brandId The ID of the brand this product belongs to.
     * @param imagePath The file path or URL of the product's image.
     * @param status The current status of the product (e.g., "Available").
     */
    public Product(String productName, String description, double price, int quantity, int categoryId, int brandId, String imagePath, String status) {
        this.productName = productName;
        this.description = description;
        this.price = price;
        this.quantity = quantity;
        this.categoryId = categoryId;
        this.brandId = brandId;
        this.imagePath = imagePath;
        this.status = status;
    }

    /**
     * Constructor for creating Product objects when retrieving from the database (with an existing ID).
     * Use this when you are fetching an existing product record from the database.
     *
     * @param productId The unique identifier of the product.
     * @param productName The name of the product.
     * @param description A brief description of the product.
     * @param price The selling price of the product.
     * @param quantity The current stock quantity of the product.
     * @param categoryId The ID of the category this product belongs to.
     * @param brandId The ID of the brand this product belongs to.
     * @param imagePath The file path or URL of the product's image.
     * @param status The current status of the product (e.g., "Available").
     */
    public Product(int productId, String productName, String description, double price, int quantity, int categoryId, int brandId, String imagePath, String status) {
        this.productId = productId;
        this.productName = productName;
        this.description = description;
        this.price = price;
        this.quantity = quantity;
        this.categoryId = categoryId;
        this.brandId = brandId;
        this.imagePath = imagePath;
        this.status = status;
    }

    // --- Getters and Setters for all fields ---
    // These methods allow other parts of your application to access and modify
    // the data encapsulated within a Product object.

    public int getProductId() {
        return productId;
    }

    public void setProductId(int productId) {
        this.productId = productId;
    }

    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    public int getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
    }

    public int getBrandId() {
        return brandId;
    }

    public void setBrandId(int brandId) {
        this.brandId = brandId;
    }

    public String getImagePath() {
        return imagePath;
    }

    public void setImagePath(String imagePath) {
        this.imagePath = imagePath;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Overrides the default toString() method to provide a more readable
     * string representation of a Product object. Useful for debugging and logging.
     *
     * @return A string containing all the attributes of the Product.
     */
    @Override
    public String toString() {
        return "Product{" +
               "productId=" + productId +
               ", productName='" + productName + '\'' +
               ", description='" + description + '\'' +
               ", price=" + price +
               ", quantity=" + quantity +
               ", categoryId=" + categoryId +
               ", brandId=" + brandId +
               ", imagePath='" + imagePath + '\'' +
               ", status='" + status + '\'' +
               '}';
    }
}
